Repository nidhaloff/igel, pull requests merged in 2020-10, with the labels that each got.

#29 Reformatted and colored igel help sections to increase readability
  igel/cli.py
  requirements.txt
  requirements_dev.txt
Labels: enhancement, feature

#31 Update Readme.tst
  README.rst
Labels: documentation

#33 Dev
  Makefile
  README.rst
  docs/conf.py
Labels: documentation, easy, enhancement

#42 implemented hyperparameter search
  HISTORY.rst
  README.rst
  examples/hyperparams-search/fit.py
  examples/hyperparams-search/igel.yaml
  igel/__init__.py
  igel/hyperparams.py
  igel/igel.py
  setup.cfg
Labels: Epic, enhancement, feature

#43 Typos
  README.rst
Labels: contribution, documentation

#44 Gui functionality
  igel/gui.py
Labels: Epic, contribution, enhancement, feature

#47 provide a way to use seed
  README.rst
  setup.py
Labels: enhancement, feature

#51 added multiple file support
  Makefile
  examples/indian-diabetes-example/fit.py
  igel/igel.py
  igel/preprocessing.py
Labels: enhancement, feature

#52 added gui
  igel/__init__.py
  igel/cli.py
Labels: Epic, enhancement, feature
