Repository nidhaloff/igel, pull requests merged in 2021-08, with the labels that each got.

#96 Addition of igel commands and short flag for help
  igel/__init__.py
  igel/__main__.py
Labels: enhancement, good first issue

#95 K medoids support
  examples/clustering/fit.py
  igel/data.py
  igel/extras/__init__.py
  igel/extras/disclaimer.md
  igel/extras/kmedoids.py
  igel/igel.py
  poetry.lock
Labels: enhancement

#98 Changed ImportError statement as from utils -> from igel.utils
  igel/data.py
  igel/extras/kmedoids.py
  igel/igel.py
Labels: bug

#100 K medians support
  docs/README.rst
  igel/data.py
  igel/extras/kmedians.py
  igel/extras/kmedoids.py
  poetry.lock
Labels: enhancement, feature
